require('components/blocks/accordion/accordion')
require('components/blocks/gallery/gallery')
require('components/blocks/hero/hero')
require('components/blocks/modal/modal')
require('components/blocks/read-more/read-more')
require('components/blocks/tabs/tabs')
require('components/global/header/search')
require('components/global/navigation/navigation')
