// require('components/blocks/search/search')
require('components/blocks/accordion/accordion')
require('components/blocks/hero/hero')
require('components/blocks/tabs/tabs')
require('components/blocks/gallery/gallery')
require('components/blocks/read-more/read-more')
require('components/global/navigation/navigation')
